[build]
  publish = "public"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  PHP_VERSION = "8.1"
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[context.production.environment]
  APP_ENV = "production"
  APP_DEBUG = "false"
